---
- name: Configure network interface
  lineinfile:
    path: /etc/dhcpcd.conf
    regex: '^interface {{ network_settings.network_interface }}'
    line: 'interface {{ network_settings.network_interface }}'
  notify:
    - Restart dhcpcd service

- name: Configure static IP address
  lineinfile:
    path: /etc/dhcpcd.conf
    regex: '^static ip_address={{ network_settings.ip_address }}'
    line: 'static ip_address={{ network_settings.ip_address }}'
  notify:
    - Restart dhcpcd service

- name: Configure network gateway
  lineinfile:
    path: /etc/dhcpcd.conf
    regex: '^static routers={{ network_settings.router_address }}'
    line: 'static routers={{ network_settings.router_address }}'
  notify:
    - Restart dhcpcd service

- name: Configure DNS address (should be loopback to point to PiHole)
  lineinfile:
    path: /etc/dhcpcd.conf
    regex: '^static domain_name_servers={{ network_settings.dns_addresses | join(" ") }}'
    line: 'static domain_name_servers={{ network_settings.dns_addresses | join(" ") }}'
  notify:
    - Restart dhcpcd service