---
- name: Ensure the root group exists
  ansible.builtin.group:
    name: "{{ sudo_group }}"
    state: present

- name: Allow sudo group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ sudo_group }}"
    line: "%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  when: enable_passwordless_sudo | default(False)

- name: Create a login user
  changed_when: false
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ user_password | string | password_hash('sha512') }}"
    groups:
      - "{{ sudo_group }}"
      - users
    state: present
    append: true
    shell: "{{ user_shell }}"
  when: enable_username_creation | default(False)

- name: Ensure group "{{ username }}" exists
  ansible.builtin.group:
    name: "{{ username }}"
    state: present
  when: enable_username_creation | default(False)
