---
pihole_enabled: false
pihole_available_externally: false

# directories
pihole_data_directory: "{{ docker_dir }}/pihole"

pihole_hostname: "pihole"

# network
pihole_port_dns: "53"
pihole_port_ui: "1080"
# pihole_port_dhcp: "67"
